# Generated by Django 4.2 on 2025-10-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Current consecutive days with quiz completion'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_quiz_date',
            field=models.DateTimeField(blank=True, help_text='Last time user completed a quiz', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text='Longest streak ever achieved'),
        ),
    ]
