# Generated by Django 5.2.7 on 2025-10-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_current_streak_user_last_quiz_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', help_text="User's theme preference", max_length=10),
        ),
    ]
