version: '3.8'

services:
  # Django Web Application
  web:
    build: .
    container_name: genex_web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DATABASE_URL=sqlite:///db.sqlite3
    depends_on:
      - sonarqube
    networks:
      - genex_network

  # SonarQube for Code Quality
  sonarqube:
    image: sonarqube:lts-community
    container_name: genex_sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - genex_network

  # Jenkins for CI/CD
  jenkins:
    image: jenkins/jenkins:lts
    container_name: genex_jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - genex_network

volumes:
  static_volume:
  media_volume:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  jenkins_home:

networks:
  genex_network:
    driver: bridge
