# Generated by Django 5.2.7 on 2025-10-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='image_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('image', 'Image'), ('other', 'Other')], max_length=10),
        ),
    ]
