# Generated by Django 4.2 on 2025-10-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_generated',
            field=models.BooleanField(default=True, verbose_name='Généré par IA'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='fr', max_length=10, verbose_name='Langue du cours'),
        ),
    ]
