# Generated by Django 5.2.7 on 2025-10-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_folder_course_folders'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='folder',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
