# Generated by Django 5.2.7 on 2025-10-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/pdfs/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu du cours'),
        ),
    ]
