# Generated by Django 5.2.7 on 2025-10-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_pdf_file_alter_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='courses/screenshots/', verbose_name="Capture d'écran"),
        ),
    ]
