# Generated by Django 5.2.7 on 2025-10-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='screenshot',
        ),
    ]
