# Generated by Django 5.2.7 on 2025-10-25 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCorrectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('best_score', models.FloatField(default=0.0)),
                ('total_time', models.FloatField(default=0.0, help_text='Temps total en minutes')),
                ('cumulative_feedback', models.TextField(blank=True)),
                ('improvement_areas', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Session de correction',
                'verbose_name_plural': 'Sessions de correction',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(help_text="Réponse soumise par l'utilisateur")),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('ai_correction', models.JSONField(default=dict, help_text="Correction automatique par l'IA")),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0, help_text='Score sur 100')),
                ('feedback', models.TextField(blank=True, help_text="Feedback détaillé de l'IA")),
                ('suggestions', models.JSONField(default=list, help_text="Suggestions d'amélioration")),
                ('correction_time', models.FloatField(default=0.0, help_text='Temps de correction en secondes')),
                ('ai_model', models.CharField(default='llama-3.1-8b-instant', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Niveau de confiance de la correction (0-1)')),
            ],
            options={
                'verbose_name': "Soumission d'exercice",
                'verbose_name_plural': "Soumissions d'exercices",
                'ordering': ['-submission_time'],
            },
        ),
        migrations.RenameIndex(
            model_name='exercise',
            new_name='exercises_e_categor_30a425_idx',
            old_name='exercises_e_category_2b8c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='exercise',
            new_name='exercises_e_is_acti_884c16_idx',
            old_name='exercises_e_is_acti_8a4b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='exercise',
            new_name='exercises_e_created_2a660d_idx',
            old_name='exercises_e_created_9b8c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='exerciseattempt',
            new_name='exercises_e_user_id_e07278_idx',
            old_name='exercises_e_user_id_8a4b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='exerciseattempt',
            new_name='exercises_e_is_corr_bd1aa5_idx',
            old_name='exercises_e_is_corr_8a4b2a_idx',
        ),
        migrations.AddField(
            model_name='exercisesession',
            name='exercises',
            field=models.ManyToManyField(through='exercises.SessionExercise', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='exercisecorrectionsession',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_sessions', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='exercisecorrectionsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='exercisesubmission',
            unique_together={('user', 'exercise')},
        ),
    ]
