# Generated by Django 5.2.7 on 2025-10-26 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercisecorrectionsession_exercisesubmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la collection', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description de la collection')),
                ('color', models.CharField(default='#dc3545', help_text='Couleur de la collection (hex)', max_length=7)),
                ('icon', models.CharField(default='fas fa-folder', help_text='Icône FontAwesome', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text="Collection visible par d'autres utilisateurs")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Collection d'exercices",
                'verbose_name_plural': "Collections d'exercices",
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercice favori',
                'verbose_name_plural': 'Exercices favoris',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.FloatField(default=0.0, help_text="Temps passé sur l'exercice en secondes")),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'exercice",
                'verbose_name_plural': "Historiques d'exercices",
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseInCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la collection")),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercisecollection')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Exercice dans collection',
                'verbose_name_plural': 'Exercices dans collections',
                'ordering': ['order', '-added_at'],
                'unique_together': {('collection', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=1, help_text='Priorité (1=haute, 5=basse)')),
                ('notes', models.TextField(blank=True, help_text="Notes personnelles sur l'exercice")),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_wishlists', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercice en liste de souhaits',
                'verbose_name_plural': 'Exercices en liste de souhaits',
                'ordering': ['priority', '-added_at'],
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
