# Generated by Django 5.2.7 on 2025-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercisecollection_exercisefavorite_exercisehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='comparison_answers',
            field=models.JSONField(default=list, help_text="Comparaison avec d'autres bonnes réponses"),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='detailed_correction',
            field=models.JSONField(default=dict, help_text='Correction ligne par ligne détaillée'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='improvement_areas',
            field=models.JSONField(default=list, help_text="Domaines d'amélioration identifiés"),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='personalized_feedback',
            field=models.TextField(blank=True, help_text='Feedback personnalisé adapté au niveau'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='strengths',
            field=models.JSONField(default=list, help_text='Points forts identifiés'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='video_explanation_url',
            field=models.URLField(blank=True, help_text="URL de la vidéo d'explication"),
        ),
    ]
