# Generated by Django 5.2.7 on 2025-10-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercisesubmission_comparison_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='explanation_video_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('custom', 'Vidéo personnalisée'), ('auto', 'Génération automatique')], default='auto', help_text="Type de vidéo d'explication", max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='explanation_video_url',
            field=models.URLField(blank=True, help_text="URL de la vidéo d'explication (YouTube, Vimeo, etc.)"),
        ),
    ]
