# Generated by Django 5.2.7 on 2025-10-27 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_explanation_video_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExerciseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, help_text='Exercice marqué comme favori')),
                ('is_wishlist', models.BooleanField(default=False, help_text='Exercice ajouté à la liste de souhaits')),
                ('is_completed', models.BooleanField(default=False, help_text='Exercice terminé')),
                ('is_in_progress', models.BooleanField(default=False, help_text='Exercice en cours')),
                ('added_to_favorites_at', models.DateTimeField(blank=True, null=True)),
                ('added_to_wishlist_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, help_text='Score obtenu (0-100)', null=True)),
                ('notes', models.TextField(blank=True, help_text="Notes personnelles de l'utilisateur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Statut d'exercice utilisateur",
                'verbose_name_plural': "Statuts d'exercices utilisateurs",
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
