# Generated by Django 5.2.7 on 2025-10-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_richexercisetype_exercisefileimport_exercisetemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisefileimport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exercisetemplate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exercisetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exercisetemplate',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='exercisetemplate',
            name='exercise_type',
        ),
        migrations.RemoveField(
            model_name='richexercise',
            name='base_exercise',
        ),
        migrations.RemoveField(
            model_name='richexercise',
            name='rich_type',
        ),
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'ordering': ['difficulty_level', 'name'], 'verbose_name': "Type d'exercice", 'verbose_name_plural': "Types d'exercices"},
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='color',
            field=models.CharField(default='#007bff', help_text='Couleur hexadécimale', max_length=7),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='difficulty_level',
            field=models.IntegerField(default=1, help_text='Niveau de complexité (1-5)'),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='icon',
            field=models.CharField(default='fas fa-question-circle', help_text='Icône FontAwesome', max_length=50),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='supports_audio',
            field=models.BooleanField(default=False, help_text="Supporte l'audio"),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='supports_drawing',
            field=models.BooleanField(default=False, help_text='Supporte le dessin'),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='supports_images',
            field=models.BooleanField(default=False, help_text='Supporte les images'),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='supports_video',
            field=models.BooleanField(default=False, help_text='Supporte la vidéo'),
        ),
        migrations.DeleteModel(
            name='ChapterExerciseGeneration',
        ),
        migrations.DeleteModel(
            name='ExerciseFileImport',
        ),
        migrations.DeleteModel(
            name='ExerciseTemplate',
        ),
        migrations.DeleteModel(
            name='RichExercise',
        ),
        migrations.DeleteModel(
            name='RichExerciseType',
        ),
    ]
