# Generated by Django 5.2.7 on 2025-10-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_remove_exercisefileimport_user_and_more'),
    ]

    operations = [
    ]
