# Generated by Django 5.2.7 on 2025-10-26 22:46

import django.db.models.deletion
import django.utils.timezone
import quizzes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=quizzes.models.generate_room_code, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Player 2'), ('ready', 'Both Players Ready'), ('playing', 'Game in Progress'), ('finished', 'Game Finished'), ('cancelled', 'Game Cancelled')], default='waiting', max_length=20)),
                ('current_question', models.IntegerField(default=0)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rooms_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_rooms_as_player2', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rooms', to='quizzes.quiz')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Room',
                'verbose_name_plural': 'Game Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.FloatField()),
                ('points_earned', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.gameroom')),
            ],
            options={
                'verbose_name': 'Game Answer',
                'verbose_name_plural': 'Game Answers',
                'unique_together': {('game_room', 'player', 'question')},
            },
        ),
    ]
